name: testproject
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and deploy
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: ${{ secrets.DOCKER_USERNAME }}/testproject
          tags: vtt23MLVC7bVtXrGH7wNBXb
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
