name: testproject
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and deploy
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: ${{ secrets.DOCKER_USERNAME }}/testproject
          tags: v7Azyvt6DJgY9FYsmWNGBQ7
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: swagger API generate
      run: |
                go get -u github.com/swaggo/swag/cmd/swag
                swag init
